[package]
name = "MadsVejrApp"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.228"
reqwest = { version = "0.12.24", features = ["json"] }
axum = "0.8.7"
tokio = { version = "1.48.0", features = ["full"] }
